language: python
cache : pip
python:
    - 2.7

before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install libblas-dev liblapack-dev
  - pip install -r requirements.txt

script:
    coverage run --source=. setup.py test

after_success:
    coveralls
